### ISSUE TITLE
Update Wiiuse build

### ISSUE THREAD

**Issue by qwertychouskie** [supertuxkart/dependencies#3]
Since https://github.com/supertuxkart/stk-code/pull/3626 was merged, the Wiiuse build here should be updated, though preferably after PR #2 is merged to avoid conflicts.

**Comment by GRA1986** [comment]
u me im a man wating for a new woman to go get me to have sex with i have not came for her me man i came by for one of by their girls one night stand or fuck buddy

**Comment by Benau** [comment]
we longer bundled wiiuse here ![](https://cdn.lihkg.com/assets/faces/pig/bye.gif)
