### ISSUE TITLE
Don't forget to release in tandem with the app releases

### ISSUE THREAD

**Issue by licaon-kter** [supertuxkart/dependencies#6]
eg. there's no release for `1.4-rc1` so for F-Droid I've picked up HEAD: https://gitlab.com/fdroid/fdroiddata/-/commit/2483d3bd68cddef494e242ec2519a26a5852a691#4272cdd1395876d76da453a1fbdd9ae5e867791f_272_292

**Comment by Benau** [comment]
final `1.4` will be tagged don't worry

**Comment by licaon-kter** [comment]
Yes, I can but I'm interested to get the same deps that you've used for your release. Eg. You've tagged the app, you've tagged the assets, just not here.

**Comment by Benau** [comment]
https://github.com/supertuxkart/dependencies/releases/tag/1.4 ![](https://cdn.lihkg.com/assets/faces/pig/bye.gif)
